TEST_VALUE:
  name: "dev_cookie"

MONGODB_CONFIG:
  name: "asself_test" #数据链接名
  type: mongodb   # 数据类型
  url: "mongodb://localhost:27017" # 数据库连接地址
  username: "root" # 数据库用户名称
  password: "123456" # 数据库连接密码
  database: "fast_gateway_test" # 数据库名称
  entities: "mongo" # 自定义加载类型
  logging: false # 数据库打印日志
  synchronize: true # 是否开启同步数据表功能
  autoLoadEntities: true
MYSQL_CONFIG:
  name: "material_test"
  type: "mysql"
  host: "localhost"
  port: "3306"
  username: "root"
  password: "123456"
  database: "material_test"
  entities: "mysql"
  logging: true
  synchronize: true